version: "3.7"

services:
  frontend:
    build: ./src/werewolf/frontend
    command: npm run dev
    volumes:
      - /code/node_modules/
      - ./src/werewolf/frontend:/code
      - static:/code/static
  backend:
    build: ./src/werewolf
    command: >
      sh -c "python src/werewolf/manage.py collectstatic --noinput &&
             python src/werewolf/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - static:/code/src/werewolf/frontend/static
      - logs:/logs/
      - /code/static
    ports:
      - "80:8000"
    depends_on:
      - frontend
      - redis
  worker:
    build: ./src/werewolf
    command: python src/werewolf/manage.py runworker werewolf-channel
    volumes:
      - .:/code
      - logs:/logs/
    depends_on:
      - redis
  redis:
    image: redis:5
    ports:
      - "6379:6379"
volumes:
  static:
  logs: