version: "3.7"

services:
  web:
    build: .
    command: python src/werewolf/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - redis
  worker:
    build: .
    command: python src/werewolf/manage.py runworker werewolf-channel
    volumes:
      - .:/code
    links:
      - redis
  redis:
    image: redis:5
    ports:
      - "6379:6379"